package com.shulha.types;

public enum Region {
    AUTONOMOUS_REPUBLIC_OF_CRIMEA,
    VINNYTSIA,
    VOLYN,
    DNIPROPETROVSK,
    DONETSK,
    ZHYTOMYR,
    ZAKARPATTIA,
    ZAPORIZHZHIA,
    IVANO_FRANKIVSK,
    KYIV,
    KIROVOHRAD,
    LUHANSK,
    LVIV,
    MYKOLAIV,
    ODESA,
    POLTAVA,
    RIVNE,
    SUMY,
    TERNOPIL,
    KHARKIV,
    KHERSON,
    KHMELNYTSKYI,
    CHERKASY,
    CHERNIVTSI,
    CHERNIHIV
}
